soong: Add libfmjni to namespaces
This fixes building the FMRadio apps

error: packages/apps/FMRadio/Android.bp:17:1: "FMRadio" depends on undefined module "libfmjni".
Module "FMRadio" is defined in namespace "." which can read these 9 namespaces:
["." "." "vendor/qcom/opensource/data-ipa-cfg-mgr-legacy-um" "hardware/qcom-caf/
msm8996" "hardware/qcom-caf/wlan" "vendor/qcom/opensource/dataservices" "vendor/lenovo/kuntao" "device/lenovo/kuntao" "vendor/dolby"]
Module "libfmjni" can be found in these namespaces: ["packages/apps/FMRadio/jni/fmr" "vendor/qcom/opensource/libfmjni"]
Or did you mean ["libgljni" "libjni" "librsjni"]?